### ISSUE TITLE
where is the menu file

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [BlackCodec/jwmappmenugen#2]
i mean where is the xml file of the program output

**Comment by BlackCodec** [comment]
The menu will be printed in stdout, so you simply need to launch it with "> your_xml_file", for example:
jwmappmenugen -i > .config/jwm/appmenu.jwmrc

**Comment by soyDESKTOP68A2MRFT** [comment]
But the question is how can i apply this xml file to my actual jwm setup if i already have a .jwmrc file

**Comment by BlackCodec** [comment]
But this problem does not concern this app but it concerns the developer jwm ...
However, there is an "include" directive:
_Other configuration files or the output of programs may be included under the JWM tag via the Include tag. The text of this tag specifies the location of additional configuration file or a program to execute. The path may be relative to the location JWM was started or be an absolute path. The file at that location is read. If the text starts with exec:, then the specified program is run. The format of the configuration file is the same as the main configuration file._ 
Source:
https://joewing.net/projects/jwm/config.html#includes
